#!/bin/bash

CWD=/home/alex/DevOps/docker-f5fpc
HOST=https://connectwdf11.sap.com
CUSER=c5281640
PIN=1988
MODE=gateway

case $1 in 
    -c|--client) 
        MODE='client'
        CODE=$2
        ;;
    -g|--gateway)
        MODE='gateway'
        CODE=$2
        ;;
    -h|--help|'')
        cat <<- EOF
Usage: sap-vpn [{-c|-g}] <6-gigits RSA-token>

Modes:
    -c|--client -   the same as you connect to VPN with pure f5fpc client.
                    All trafic goes thru VPN
    -g|--gateway -  limited mode, where you can configure traffic with routes to 
                    make use VPN only for requests that you choise.
Default values:
dir:    $CWD
host:   $HOST
user:   $CUSER
pin:    $PIN
mode:   $MODE
EOF
        exit 0
        ;;

    *)
        CODE=$1
        ;;
esac

sudo $CWD/f5fpc-vpn.sh $MODE --host $HOST --user $CUSER --password "${PIN}${CODE}"

